- :date: 12-Mar-2020
  :jira_id: '3530'
  :description: |-
    Orchids: change the name-match-no-primary: directive to find Orchids with at least one matching name but no matching name with a primary instance.
- :date: 12-Mar-2020
  :jira_id: '3530'
  :description: |-
    Orchids: records were erroneously showing as 'No Primary Instance' when there were multiple matching names, one of which had no primary instance.  Now it has to be all of any matching names having no primary instance.
- :date: 12-Mar-2020
  :release: true
- :date: 11-Mar-2020
  :jira_id: 
  :description: |-
    Orchids: added search on the comment field, with help and examples - no jira.
- :date: 11-Mar-2020
  :jira_id: '3529'
  :description: |-
    Orchids: when editing raw synonym data, the synonym type field options include heterotypic and homotypic, so you can see the raw value, but these options are disabled so you cannot choose them.
- :date: 25-Feb-2020
  :jira_id: '3461'
  :description: |-
    Orchids: the Batch tab now lets you add orchids to the current draft tree.  This is an early version of the feature, released for review and improvement. The feature is switched off by default.
- :date: 28-Feb-2020
  :release: true
- :date: 25-Feb-2020
  :jira_id: '3525'
  :description: |-
    Orchids: synonym type is now required and you cannot add or save a synonym without a synonym type; also the drop-down list of synonym type options has no blank entry now.
- :date: 25-Feb-2020
  :jira_id: '3524'
  :description: |-
    Orchids: add query to find raw data synonyms missing a synonym type - 'is-syn-but-no-syn-type:' 
- :date: 03-Feb-2020
  :release: true
- :date: 28-Jan-2020
  :jira_id: '3503'
  :description: |-
    Clicking the Name details More tab now displays the second line of tabs but also with the Comment tab active.  This was normal behaviour before NSL-3394 and is now restored.
- :date: 23-Jan-2020
  :release: true
- :date: 17-Jan-2020
  :jira_id: '3495'
  :description: |-
    Two new instance query directives: note-has-carriage-return and note-updated-by, with query help and examples; also showing meta data for instance notes.
- :date: 16-Jan-2020
  :release: true
