---
- :date: 07-Mar-2019
  :release: true
- :date: 06-03-2019
  :jira_id: '3173'
  :description: |-
    Change placement of edition on reference details tab.
- :date: 26-02-2019
  :jira_id: '2426'
  :description: |-
    Search for text in a particular type of instance note.
- :date: 22-Feb-2019
  :release: true
- :date: 20-02-2019
  :jira_id: '3217'
  :description: |-
    Extract and display the error message from the name delete service when it fails.
- :date: 04-Feb-2019
  :release: true
