- :date: 28-Jan-2020
  :jira_id: '3503'
  :description: |-
    Clicking the Name details More tab now displays the second line of tabs but also with the Comment tab active.  This was normal behaviour before NSL-3394 and is now restored.
- :date: 23-Jan-2020
  :release: true
- :date: 17-Jan-2020
  :jira_id: '3495'
  :description: |-
    Two new instance query directives: note-has-carriage-return and note-updated-by, with query help and examples; also showing meta data for instance notes.
- :date: 16-Jan-2020
  :release: true
