- :date: 24-Apr-2020
  :jira_id: '3542'
  :description: |-
    Changed update name_path to do a bulk update of name paths to update all child names.
- :date: 24-Apr-2020
  :release: true
- :date: 13-Mar-2020
  :jira_id: '3481'
  :description: |-
    Orchids: prevent a match being saved for an orchid that is a synonym-without-a-synonym-type, and make it clear that is a problem the user can fix
- :date: 13-Mar-2020
  :jira_id: '3530'
  :description: |-
    Orchids: consider a broader set of name matches, particularly on the Details tab, by no longer excluding names that are duplicates or have no instances.
- :date: 13-Mar-2020
  :jira_id: '3536'
  :description: |-
    Upgrade Rails to 4.2.11.1 for security
- :date: 12-Mar-2020
  :release: true
- :date: 11-Mar-2020
  :jira_id: 
  :description: |-
    Orchids: added search on the comment field, with help and examples - no jira.
- :date: 11-Mar-2020
  :jira_id: '3529'
  :description: |-
    Orchids: when editing raw synonym data, the synonym type field options include heterotypic and homotypic, so you can see the raw value, but these options are disabled so you cannot choose them.
- :date: 25-Feb-2020
  :jira_id: '3461'
  :description: |-
    Orchids: the Batch tab now lets you add orchids to the current draft tree.  This is an early version of the feature, released for review and improvement. The feature is switched off by default.
- :date: 28-Feb-2020
  :release: true
- :date: 25-Feb-2020
  :jira_id: '3525'
  :description: |-
    Orchids: synonym type is now required and you cannot add or save a synonym without a synonym type; also the drop-down list of synonym type options has no blank entry now.
- :date: 25-Feb-2020
  :jira_id: '3524'
  :description: |-
    Orchids: add query to find raw data synonyms missing a synonym type - 'is-syn-but-no-syn-type:' 
- :date: 03-Feb-2020
  :release: true
- :date: 28-Jan-2020
  :jira_id: '3503'
  :description: |-
    Clicking the Name details More tab now displays the second line of tabs but also with the Comment tab active.  This was normal behaviour before NSL-3394 and is now restored.
- :date: 23-Jan-2020
  :release: true
- :date: 17-Jan-2020
  :jira_id: '3495'
  :description: |-
    Two new instance query directives: note-has-carriage-return and note-updated-by, with query help and examples; also showing meta data for instance notes.
- :date: 16-Jan-2020
  :release: true
