---
- :date: 7-Sep-2018
  :release: true
- :date: 22-Aug-2018
  :jira_id: '2955'
  :description: |-
    Add link to show name in new search.
- :date: 16-Aug-2018
  :jira_id: '2928'
  :description: |-
    The Name &gt; Copy tab has a link that appears after a copy is completed.  That link was broken and it is now fixed.
- :date: 16-Aug-2018
  :release: true
- :date: 6-Aug-2018
  :jira_id: '2757'
  :description: |-
    Changed the name of the new scientific name family and above. Changed the order of parent and Family and automatically set family from the parent.
- :date: 3-Aug-2018
  :jira_id: '2875'
  :description: |-
    Added "tree-dist-matches:" and "tree-comment-matches:" search option to instance search and changed "apc-dist-match" to "apc-dist-note-match" and added "apc-comment-note=match"
- :date: 4-Jul-2018
  :jira_id: '2883'
  :description: |-
    Fix error when creating hybrid names.
- :date: 4-Jul-2018
  :jira_id: '2857'
  :description: |-
    Warn when editing or deleting the synonymy of an accepted instance.
- :date: 2-Jul-2018
  :jira_id: '2773'
  :description: |-
    Add confirm remove and warning of sub taxa removal when removing a taxon from the draft tree.
- :date: 22-Jun-2018
  :jira_id: '2842'
  :description: |-
    Add a check if a name needs a Family. Alter the name edit form to leave out Family if not required.
- :date: 22-Jun-2018
  :jira_id: '2831'
  :description: |-
    Allow editing of existing APC comment and distribution notes. Note that notes that are on a tree should be removed from instance notes.
- :date: 13-Jun-2018
  :jira_id: '2438'
  :description: |-
    New tree structure and editing.
- :date: 13-Jun-2018
  :release: true
- :date: 29-Mar-2018
  :jira_id: 
  :description: |-
    Add link to new search and add menu options to turn Editor links on and off in new search.
- :date: 23-Feb-2018
  :jira_id: '2638'
  :description: |-
    Move feedback link back to main page; move feedback JavaScript to the configuration file.
- :date: 09-Feb-2018
  :jira_id: '2638'
  :description: |-
    Add feedback on/off configuration switch.
- :date: 02-Feb-2018
  :jira_id: ''
  :description: |-
    Remove hard-coded references to 'NSL' etc with pull-request from Arnab for DAWR.
- :date: 09-Feb-2018
  :jira_id: '2638'
  :description: |-
    Add feedback on/off configuration switch.
- :date: 02-Feb-2018
  :release: true
- :date: 25-Jan-2018
  :jira_id: '2499'
  :description: |-
    Correct the ordering of instances by page.

