---
- :date: 29-Mar-2018
  :jira_id: 
  :description: |-
    Add link to new search and add menu options to turn Editor links on and off in new search.
- :date: 23-Feb-2018
  :jira_id: '2638'
  :description: |-
    Move feedback link back to main page; move feedback JavaScript to the configuration file.
- :date: 09-Feb-2018
  :jira_id: '2638'
  :description: |-
    Add feedback on/off configuration switch.
- :date: 02-Feb-2018
  :jira_id: ''
  :description: |-
    Remove hard-coded references to 'NSL' etc with pull-request from Arnab for DAWR.
- :date: 09-Feb-2018
  :jira_id: '2638'
  :description: |-
    Add feedback on/off configuration switch.
- :date: 02-Feb-2018
  :release: true
- :date: 25-Jan-2018
  :jira_id: '2499'
  :description: |-
    Correct the ordering of instances by page.
- :date: 13-Jun-2018
  :jira_id: '2438'
  :description: |-
    New tree structure and editing.
- :date: 22-Jun-2018
  :jira_id: '2842'
  :description: |-
    Add a check if a name needs a Family. Alter the name edit form to leave out Family if not required.
- :date: 22-Jun-2018
  :jira_id: '2831'
  :description: |-
    Allow editing of existing APC comment and distribution notes. Note that notes that are on a tree should be removed from instance notes.
