---
- :date: 01-Nov-2019
  :jira_id: '3418'
  :description: |-
    Add 'Created' message for create Orchid raw synonym.
- :date: 31-Oct-2019
  :jira_id: '3418'
  :description: |-
    Fix display bug noticed on Wednesday, show record type beside 'Already the preferred match for...' (including for misapplieds); now also allowing Create Synonym for an accepted taxon.
- :date: 30-Oct-2019
  :jira_id: '3418'
  :description: |-
    More hybrid-related queries, with examples.  Other minor fixes.
- :date: 30-Oct-2019
  :jira_id: '3417'
  :description: |-
    Orchid loading: you can now delete raw records, provided they have no synonyms or preferred matches; also you can now clear out preferred matches for a raw record.
- :date: 29-Oct-2019
  :jira_id: '3418'
  :description: |-
    Orchid loading: now showing all raw fields; added hybrid-related queries; added alt_taxon_for_matching which you can enter and query and which is used for matching.
- :date: 23-Oct-2019
  :jira_id: '3397'
  :description: |-
    Orchid loading: now has an edit tab for orchids allowing fine tuning of instance type.  Also honouring the partly (p.p.) field when assigning instance type.
- :date: 23-Oct-2019
  :jira_id: '3397'
  :description: |-
    Orchid loading: now adding instances and instance type for every preferred name link.
- :date: 21-Oct-2019
  :jira_id: '3397'
  :description: |-
    Orchid data loading now allows multiple preferred name/instances for misapplieds - other related changes.
- :date: 18-Oct-2019
  :jira_id: '3397'
  :description: |-
    Orchid data loading features for vascular shard - switchable via configuration, so should not impact other shards.
- :date: 31-Jul-2019
  :release: true
- :date: 31-Jul-2019
  :jira_id: '3339'
  :description: |-
    Widen Reference edit year field.
- :date: 31-Jul-2019
  :release: true
- :date: 18-Jul-2019
  :jira_id: '3311'
  :description: |-
    Add data entry for reference day, month and year of publication which are stored in iso_publication_date.
    Year field is deprecated.
- :date: 04-Jul-2019
  :release: true
- :date: 03-Jul-2019
  :jira_id: '3318'
  :description: |-
    Remove incorrect tree ticks/crosses in cross-references on the details tab.
- :date: 13-Jun-2019
  :release: true
- :date: 12-Jun-2019
  :jira_id: '3281'
  :description: |-
    Allow override for creating or updating duplicate standalone or additional primary instances.
- :date: 03-Jun-2019
  :jira_id: '3303'
  :description: |-
    Added report excluded-name-with-distribution: to list excluded names with a distribution.
- :date: 03-Jun-2019
  :jira_id: '1951'
  :description: |-
    Removed the "accepted-name-synony-of-accepted-name" report as it used the old tree and didn't work. Functionality
    replaced by tree validation report.
- :date: 30-May-2019
  :jira_id: '1622'
  :description: |-
    New distribution editing for the tree.
- :date: 09-May-2019
  :release: true
- :date: 06-May-2019
  :jira_id: '3161'
  :description: |-
    Show the excluded name icon for excluded names on the instance details tab
    wherever we show the accepted name icon for accepted names.
- :date: 03-May-2019
  :jira_id: '3189'
  :description: |-
    Added two name search directives: accepted-in-accepted-tree and excluded-in-accepted-tree.
- :date: 02-May-2019
  :release: true
- :date: 26-Apr-2019
  :jira_id: '2343'
  :description: |-
    Prevent addition of notes and adnots in most synonymy instances.
- :date: 18-Apr-2019
  :release: true
- :date: 05-Apr-2019
  :jira_id: '3182'
  :description: |-
    Fixed the copy name feature.
- :date: 05-Apr-2019
  :release: true
- :date: 02-Apr-2019
  :jira_id: '614'
  :description: |-
    Add ability to change password.
- :date: 27-Mar-2019
  :jira_id: '3235'
  :description: |-
    Remove special formatting for old versions of firefox.
- :date: 07-Mar-2019
  :release: true
- :date: 06-Mar-2019
  :jira_id: '3173'
  :description: |-
    Change placement of edition on reference details tab.
- :date: 26-Feb-2019
  :jira_id: '2426'
  :description: |-
    Search for text in a particular type of instance note.
- :date: 22-Feb-2019
  :release: true
- :date: 20-Feb-2019
  :jira_id: '3217'
  :description: |-
    Extract and display the error message from the name delete service when it fails.
- :date: 04-Feb-2019
  :release: true
