# Get database config and credentials.
<% if ENV['EDITOR_CONFIGDB_FILE'] %>
<%= ERB.new(File.read("#{ENV['EDITOR_CONFIGDB_FILE']}")).result %>
<% else %>
<%= ERB.new(File.read("#{ENV['HOME']}/.nsl/editor-database.yml")).result %>
<% end %>

